# Generated by Django 2.2.1 on 2019-06-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190610_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNUM',
        ),
    ]
